name: benchmarks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - boost_unordered_flat_map_fil-c_memory

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:            
          - name: clang-x64
            compiler: clang++-18
            architecture: -m64
            sourcefile: running_insertion.cpp
            compileroptions: -std=c++20 -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            # os: ubuntu-20.04
            os: [self-hosted, linux, x64]
            install: clang
            command: sudo /usr/bin/time -v cgexec -g memory,cpu:shield sudo -u gha ./benchmark
          - name: clang-x64
            compiler: clang++-18
            architecture: -m64
            sourcefile: running_erasure.cpp
            compileroptions: -std=c++20 -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            # os: ubuntu-20.04
            os: [self-hosted, linux, x64]
            install: clang
            command: sudo /usr/bin/time -v cgexec -g memory,cpu:shield sudo -u gha ./benchmark
          - name: clang-x64
            compiler: clang++-18
            architecture: -m64
            sourcefile: scattered_lookup.cpp
            compileroptions: -std=c++20 -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            # os: ubuntu-20.04
            os: [self-hosted, linux, x64]
            install: clang
            command: sudo /usr/bin/time -v cgexec -g memory,cpu:shield sudo -u gha ./benchmark

          - name: clang-x64
            compiler: clang++-18
            architecture: -m64
            sourcefile: running_insertion.cpp
            compileroptions: -fno-omit-frame-pointer -fsanitize=address -gline-tables-only -std=c++20 -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            # os: ubuntu-20.04
            os: [self-hosted, linux, x64]
            install: clang
            command: sudo /usr/bin/time -v cgexec -g memory,cpu:shield sudo -u gha ./benchmark
          - name: clang-x64
            compiler: clang++-18
            architecture: -m64
            sourcefile: running_erasure.cpp
            compileroptions: -fno-omit-frame-pointer -fsanitize=address -gline-tables-only -std=c++20 -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            # os: ubuntu-20.04
            os: [self-hosted, linux, x64]
            install: clang
            command: sudo /usr/bin/time -v cgexec -g memory,cpu:shield sudo -u gha ./benchmark
          - name: clang-x64
            compiler: clang++-18
            architecture: -m64
            sourcefile: scattered_lookup.cpp
            compileroptions: -fno-omit-frame-pointer -fsanitize=address -gline-tables-only -std=c++20 -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            # os: ubuntu-20.04
            os: [self-hosted, linux, x64]
            install: clang
            command: sudo /usr/bin/time -v cgexec -g memory,cpu:shield sudo -u gha ./benchmark

          - name: clang-x64
            compiler: fil++
            architecture: -m64
            sourcefile: running_insertion.cpp
            compileroptions: -std=c++20 -O3 -DNDEBUG -DHAVE_ABSEIL -DBOOST_ALL_NO_EMBEDDED_GDB_SCRIPTS
            outputfile: benchmark
            # os: ubuntu-20.04
            os: [self-hosted, linux, x64]
            install: clang
            command: sudo /usr/bin/time -v cgexec -g memory,cpu:shield sudo -u gha ./benchmark
          - name: clang-x64
            compiler: fil++
            architecture: -m64
            sourcefile: running_erasure.cpp
            compileroptions: -std=c++20 -O3 -DNDEBUG -DHAVE_ABSEIL -DBOOST_ALL_NO_EMBEDDED_GDB_SCRIPTS
            outputfile: benchmark
            # os: ubuntu-20.04
            os: [self-hosted, linux, x64]
            install: clang
            command: sudo /usr/bin/time -v cgexec -g memory,cpu:shield sudo -u gha ./benchmark
          - name: clang-x64
            compiler: fil++
            architecture: -m64
            sourcefile: scattered_lookup.cpp
            compileroptions: -std=c++20 -O3 -DNDEBUG -DHAVE_ABSEIL -DBOOST_ALL_NO_EMBEDDED_GDB_SCRIPTS
            outputfile: benchmark
            # os: ubuntu-20.04
            os: [self-hosted, linux, x64]
            install: clang
            command: sudo /usr/bin/time -v cgexec -g memory,cpu:shield sudo -u gha ./benchmark
                       
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        if: matrix.install
        run: |
          # sudo -E apt-add-repository -y ppa:ubuntu-toolchain-r/test
          if uname -p | grep -q 'x86_64'; then sudo dpkg --add-architecture i386 ; fi
          sudo apt-get update
          sudo apt-get install -y ${{matrix.install}}
      - name: Install Fil-C
        if: startsWith(matrix.compiler, 'fil++')
        run: |
          set -xe
          sudo mkdir -p /opt/downloads
          sudo rm -rf /opt/fil
          cd /opt/downloads
          fil_c_version="0.674"
          sudo wget "https://github.com/pizlonator/fil-c/releases/download/v${fil_c_version}/optfil-${fil_c_version}-linux-x86_64.tar.xz"
          sudo tar -xvJf "optfil-${fil_c_version}-linux-x86_64.tar.xz"
          cd "optfil-${fil_c_version}-linux-x86_64"
          echo -e "YES\nYES" | sudo ./setup.sh
          echo "/opt/fil/bin" >> $GITHUB_PATH
      - name: Install Boost
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/boostorg/boost.git boost-root
          cd boost-root
          git checkout develop
          git submodule update --init
          ./bootstrap.sh
          ./b2 -d0 headers
      - name: Install Abseil
        run: |
          cd $GITHUB_WORKSPACE
          git clone -b lts_2022_06_23 https://github.com/abseil/abseil-cpp.git abseil-root
      - name: Compile
        run: |
          cd $GITHUB_WORKSPACE
          ${{matrix.compiler}} --version
          ${{matrix.compiler}} ${{matrix.sourcefile}} ${{matrix.architecture}} ${{matrix.compileroptions}} -o ${{matrix.outputfile}} -I$GITHUB_WORKSPACE/boost-root -I$GITHUB_WORKSPACE/abseil-root
      - name: Run benchmarks
        run: |
          if [ -n "${{matrix.xcode_version}}" ]; then
              DEVELOPER_DIR=/Applications/Xcode-${{matrix.xcode_version}}.app/Contents/Developer
          fi
          ${{matrix.command}}
